Issue with depenency on targets groups of ALB
Error: Invalid for_each argument
  on alb.tf line 49, in resource "aws_lb_target_group_attachment" "elasticsearch_api":
  49:   for_each = toset(flatten(values(module.elasticsearch).*.cold_node_ips))
The "for_each" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the for_each depends on.

Reworked the module etc to address issue.